services:

  nginx:
    build:
      context: ./docker/nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
    restart: always
    networks:
      billing:
        ipv4_address: 10.1.0.10

  postgres:
    image: postgres:latest
    volumes:
      - pg_billing:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      billing:

  redis:
    image: redis:5.0
    networks:
      billing:

  nx:
    image: node:19.6
    command: npm run serve
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    networks:
      billing:
        ipv4_address: 10.1.0.30

volumes:
  pg_billing:

networks:
  billing:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.1

